[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
prediction_market_program = "5xmuKFcMjHDuxUUNzaRxmncjASqbEA8v8sBJmRQAfdXa"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
